# Web Scraping a la página de Chartmasters

URL: 'https://chartmasters.org/most-streamed-artists-ever-on-spotify/'

Se realiza Web Scraping con Beautiful Soup a la página de Chartmasters para sacar un DataFrame con los artistas con más reproducciones en Spotify.

In [3]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

# Hacer la solicitud HTTP
url = 'https://chartmasters.org/most-streamed-artists-ever-on-spotify/'
response = requests.get(url)

# Analizar el contenido HTML de la página web
soup = BeautifulSoup(response.content, 'html.parser')

# Encontrar la tabla de artistas
table = soup.find('table')

# Crear una lista vacía para almacenar los datos
data = []

# Encontrar todas las filas de la tabla, excepto la primera (que contiene los encabezados de las columnas)
rows = table.find_all('tr')[1:]

# Iterar a través de cada fila y obtener los datos
for row in rows:
    cols = row.find_all('td')[2:]
    cols = [col.text.strip() for col in cols]
    data.append(cols)

In [4]:
data

[['Drake2 day(s) old data',
  '56,194,988,475',
  '282',
  '7',
  '148',
  '275',
  '279',
  '20,329,715,771'],
 ['Bad Bunny2 day(s) old data',
  '51,189,983,147',
  '162',
  '9',
  '121',
  '157',
  '160',
  '7,541,244,342'],
 ['Taylor SwiftUp to date data',
  '42,204,571,789',
  '353',
  '2',
  '128',
  '277',
  '341',
  '471,196,255'],
 ['Ed SheeranUp to date data',
  '41,120,157,022',
  '251',
  '11',
  '67',
  '187',
  '228',
  '3,082,734,708'],
 ['The Weeknd1 day(s) old data',
  '39,704,788,932',
  '219',
  '10',
  '80',
  '148',
  '185',
  '6,540,530,184'],
 ['Justin BieberUp to date data',
  '35,225,977,864',
  '226',
  '8',
  '61',
  '176',
  '197',
  '7,677,942,155'],
 ['Ariana GrandeUp to date data',
  '35,000,764,144',
  '183',
  '9',
  '73',
  '132',
  '178',
  '2,215,911,852'],
 ['EminemUp to date data',
  '33,760,538,200',
  '285',
  '6',
  '67',
  '229',
  '264',
  '4,567,249,852'],
 ['BTSUp to date data',
  '32,095,643,864',
  '263',
  '3',
  '105',
  '214',
  '263',
  '375,428,177'],
 ['Post Malone2 day(s) old data',
  '31,942,500,341',
  '99',
  '9',
  '59',
  '81',
  '83',
  '2,908,098,424'],
 ['J BalvinUp to date data',
  '29,457,751,062',
  '252',
  '4',
  '72',
  '160',
  '236',
  '8,604,998,321'],
 ['Kanye West1 day(s) old data',
  '28,346,530,222',
  '240',
  '2',
  '67',
  '197',
  '223',
  '6,198,370,769'],
 ['Billie EilishUp to date data',
  '26,122,877,545',
  '66',
  '5',
  '49',
  '60',
  '63',
  '46,594'],
 ['Coldplay1 day(s) old data',
  '24,635,157,072',
  '299',
  '7',
  '36',
  '185',
  '280',
  '0'],
 ['Juice WRLD1 day(s) old data',
  '24,571,142,646',
  '118',
  '3',
  '64',
  '116',
  '117',
  '4,750,691,818'],
 ['Dua LipaUp to date data',
  '24,360,913,756',
  '198',
  '8',
  '37',
  '86',
  '169',
  '246,816,234'],
 ['Imagine Dragons2 day(s) old data',
  '24,144,876,094',
  '190',
  '6',
  '43',
  '117',
  '156',
  '73,327,229'],
 ['XXXTENTACION2 day(s) old data',
  '23,411,694,483',
  '139',
  '8',
  '45',
  '104',
  '135',
  '2,842,508,810'],
 ['Rihanna2 day(s) old data',
  '23,242,724,571',
  '282',
  '5',
  '48',
  '115',
  '213',
  '7,357,858,759'],
 ['Ozuna2 day(s) old data',
  '23,174,510,877',
  '254',
  '1',
  '56',
  '167',
  '222',
  '7,927,744,280'],
 ['Khalid2 day(s) old data',
  '22,376,640,280',
  '120',
  '7',
  '45',
  '97',
  '113',
  '3,068,505,031'],
 ['Maroon 5Up to date data',
  '21,564,486,341',
  '241',
  '9',
  '31',
  '113',
  '199',
  '19,400'],
 ['David Guetta2 day(s) old data',
  '21,037,636,659',
  '731',
  '1',
  '47',
  '158',
  '426',
  '1,790,692,770'],
 ['Travis Scott2 day(s) old data',
  '20,978,753,941',
  '113',
  '4',
  '51',
  '90',
  '108',
  '11,894,271,023'],
 ['Shawn Mendes1 day(s) old data',
  '20,305,953,015',
  '128',
  '5',
  '34',
  '95',
  '126',
  '58,741,442'],
 ['Bruno Mars2 day(s) old data',
  '20,071,894,514',
  '80',
  '6',
  '32',
  '61',
  '75',
  '4,756,086,638'],
 ['Daddy Yankee2 day(s) old data',
  '19,788,590,136',
  '361',
  '4',
  '46',
  '111',
  '251',
  '6,204,689,255'],
 ['Kendrick Lamar2 day(s) old data',
  '19,752,715,305',
  '121',
  '2',
  '46',
  '113',
  '117',
  '9,186,878,482'],
 ['Sam SmithUp to date data',
  '19,291,675,062',
  '166',
  '4',
  '36',
  '89',
  '149',
  '286,579,426'],
 ['Calvin Harris2 day(s) old data',
  '19,211,050,948',
  '236',
  '4',
  '31',
  '89',
  '192',
  '498,225,222'],
 ['Queen2 day(s) old data',
  '17,981,657,904',
  '588',
  '5',
  '25',
  '102',
  '415',
  '40,762,552'],
 ['BeyoncéUp to date data',
  '17,464,790,481',
  '368',
  '1',
  '40',
  '174',
  '270',
  '2,203,446,971'],
 ['Future2 day(s) old data',
  '16,983,372,361',
  '506',
  '2',
  '36',
  '242',
  '371',
  '10,617,627,252'],
 ['One Direction1 day(s) old data',
  '16,955,785,664',
  '124',
  '0',
  '48',
  '100',
  '118',
  '0'],
 ['Lady GagaUp to date data',
  '16,692,338,408',
  '317',
  '1',
  '31',
  '113',
  '209',
  '101,417,499'],
 ['Chris Brown2 day(s) old data',
  '16,664,135,674',
  '397',
  '0',
  '40',
  '204',
  '330',
  '8,776,098,430'],
 ['J. Cole2 day(s) old data',
  '16,310,879,983',
  '137',
  '2',
  '40',
  '114',
  '137',
  '3,613,252,992'],
 ['The Chainsmokers2 day(s) old data',
  '16,291,877,053',
  '214',
  '4',
  '28',
  '81',
  '173',
  '414,385,978'],
 ['Harry StylesUp to date data',
  '16,186,183,010',
  '39',
  '4',
  '36',
  '37',
  '38',
  '1,855,546'],
 ['AdeleUp to date data',
  '15,972,250,994',
  '70',
  '5',
  '28',
  '59',
  '69',
  '42,018,170'],
 ['Nicki MinajUp to date data',
  '15,955,338,056',
  '174',
  '3',
  '37',
  '124',
  '165',
  '12,285,306,349'],
 ['Selena GomezUp to date data',
  '15,248,609,315',
  '141',
  '3',
  '26',
  '84',
  '127',
  '2,198,281,151'],
 ['The Beatles2 day(s) old data',
  '15,195,890,140',
  '852',
  '0',
  '41',
  '193',
  '487',
  '0'],
 ['HalseyUp to date data',
  '15,114,256,479',
  '181',
  '3',
  '25',
  '102',
  '137',
  '2,683,837,808'],
 ['Anuel AAUp to date data',
  '15,090,394,549',
  '189',
  '1',
  '34',
  '150',
  '183',
  '5,992,535,331'],
 ['Sia1 day(s) old data',
  '14,842,306,153',
  '337',
  '2',
  '27',
  '111',
  '248',
  '5,240,142,791'],
 ['Lana Del ReyUp to date data',
  '14,651,595,109',
  '168',
  '0',
  '47',
  '126',
  '158',
  '1,310,574,137'],
 ['Linkin Park2 day(s) old data',
  '14,259,886,196',
  '351',
  '2',
  '32',
  '118',
  '283',
  '50,856,419'],
 ['Maluma2 day(s) old data',
  '14,256,498,752',
  '202',
  '1',
  '38',
  '136',
  '190',
  '6,755,846,930'],
 ['Rauw Alejandro2 day(s) old data',
  '14,204,041,868',
  '193',
  '1',
  '33',
  '113',
  '163',
  '2,920,812,455'],
 ['Lil Uzi Vert2 day(s) old data',
  '14,203,267,890',
  '143',
  '1',
  '35',
  '130',
  '141',
  '9,053,761,851'],
 ['Marshmello2 day(s) old data',
  '14,108,688,280',
  '170',
  '4',
  '22',
  '92',
  '163',
  '603,314,953'],
 ['Katy PerryUp to date data',
  '13,993,143,208',
  '182',
  '1',
  '31',
  '89',
  '145',
  '1,287,850,866'],
 ['Twenty One Pilots2 day(s) old data',
  '13,669,856,053',
  '89',
  '3',
  '37',
  '75',
  '89',
  '0'],
 ['Arctic Monkeys2 day(s) old data',
  '13,352,206,529',
  '143',
  '3',
  '27',
  '99',
  '143',
  '0'],
 ['Avicii1 day(s) old data',
  '13,335,342,450',
  '252',
  '3',
  '19',
  '92',
  '163',
  '601,882,972'],
 ['KAROL GUp to date data',
  '13,282,936,318',
  '101',
  '2',
  '35',
  '82',
  '96',
  '585,742,513'],
 ['Kygo2 day(s) old data',
  '13,216,590,286',
  '115',
  '1',
  '33',
  '91',
  '112',
  '1,127,768,660'],
 ['Doja CatUp to date data',
  '13,138,158,376',
  '86',
  '3',
  '27',
  '66',
  '83',
  '2,526,589,101'],
 ['Camila Cabello1 day(s) old data',
  '12,656,026,058',
  '64',
  '2',
  '24',
  '48',
  '59',
  '2,285,472,090'],
 ['ShakiraUp to date data',
  '12,440,971,197',
  '238',
  '1',
  '33',
  '95',
  '204',
  '1,505,591,314'],
 ['Farruko2 day(s) old data',
  '12,423,170,993',
  '341',
  '2',
  '29',
  '119',
  '296',
  '7,748,623,680'],
 ['Red Hot Chili Peppers2 day(s) old data',
  '12,036,630,681',
  '282',
  '2',
  '20',
  '128',
  '248',
  '0'],
 ['Miley CyrusUp to date data',
  '11,686,992,888',
  '211',
  '1',
  '20',
  '92',
  '180',
  '988,062,170'],
 ['21 Savage2 day(s) old data',
  '11,642,083,813',
  '175',
  '1',
  '31',
  '106',
  '147',
  '7,588,824,429'],
 ['OneRepublic2 day(s) old data',
  '11,422,264,875',
  '166',
  '1',
  '28',
  '80',
  '142',
  '272,342,846'],
 ['Demi LovatoUp to date data',
  '11,307,688,435',
  '251',
  '1',
  '23',
  '103',
  '211',
  '1,487,196,473'],
 ['Jason Derulo2 day(s) old data',
  '11,169,462,438',
  '197',
  '2',
  '26',
  '68',
  '136',
  '1,539,190,032'],
 ['Michael Jackson1 day(s) old data',
  '10,788,611,460',
  '342',
  '1',
  '26',
  '94',
  '236',
  '573,779,524'],
 ['Charlie PuthUp to date data',
  '10,722,322,360',
  '117',
  '3',
  '15',
  '63',
  '106',
  '251,214,375'],
 ['SZAUp to date data',
  '10,671,034,732',
  '76',
  '2',
  '26',
  '66',
  '75',
  '2,619,659,124'],
 ['Pitbull2 day(s) old data',
  '10,255,165,646',
  '399',
  '1',
  '21',
  '89',
  '221',
  '3,298,816,242'],
 ['Olivia Rodrigo1 day(s) old data',
  '10,229,809,085',
  '37',
  '4',
  '13',
  '25',
  '35',
  '2,057,237'],
 ['Pop Smoke2 day(s) old data',
  '10,201,412,545',
  '100',
  '0',
  '22',
  '86',
  '98',
  '1,041,455,048'],
 ['Mac Miller9 day(s) old data',
  '10,182,597,327',
  '211',
  '0',
  '26',
  '137',
  '193',
  '756,609,671'],
 ['Lil Baby2 day(s) old data',
  '10,033,593,565',
  '170',
  '1',
  '20',
  '123',
  '168',
  '11,143,064,614'],
 ['Metallica1 day(s) old data',
  '9,905,902,565',
  '818',
  '1',
  '17',
  '115',
  '287',
  '14,513,655'],
 ['Elton John2 day(s) old data',
  '9,774,449,296',
  '945',
  '1',
  '21',
  '68',
  '284',
  '333,051,747'],
 ['Lil Nas X1 day(s) old data',
  '9,769,971,415',
  '35',
  '3',
  '14',
  '32',
  '34',
  '0'],
 ['Myke Towers2 day(s) old data',
  '9,719,425,626',
  '172',
  '0',
  '28',
  '100',
  '164',
  '5,728,241,932'],
 ['Cardi BUp to date data',
  '9,621,725,916',
  '71',
  '2',
  '18',
  '55',
  '69',
  '6,489,272,041'],
 ['Panic! At The DiscoUp to date data',
  '9,621,460,658',
  '149',
  '1',
  '24',
  '80',
  '140',
  '710,272,844'],
 ['Metro Boomin11 day(s) old data',
  '9,587,729,058',
  '163',
  '1',
  '25',
  '87',
  '112',
  '224,392,046'],
 ['Lil Wayne2 day(s) old data',
  '9,563,845,350',
  '496',
  '1',
  '20',
  '120',
  '328',
  '15,242,387,724'],
 ['Ellie Goulding2 day(s) old data',
  '9,493,471,639',
  '190',
  '1',
  '16',
  '73',
  '144',
  '661,972,420'],
 ['Alan Walker2 day(s) old data',
  '9,489,109,012',
  '178',
  '1',
  '18',
  '74',
  '143',
  '1,982,716,691'],
 ['Young Thug2 day(s) old data',
  '9,463,754,240',
  '364',
  '0',
  '21',
  '137',
  '219',
  '10,339,385,064'],
 ['Nicky Jam2 day(s) old data',
  '9,462,992,159',
  '217',
  '0',
  '26',
  '85',
  '155',
  '10,541,205,489'],
 ['Lil Peep2 day(s) old data',
  '9,344,508,243',
  '111',
  '0',
  '24',
  '93',
  '111',
  '819,047,361'],
 ['G-Eazy2 day(s) old data',
  '9,243,691,156',
  '227',
  '1',
  '18',
  '115',
  '211',
  '2,254,295,513'],
 ['AC/DCUp to date data',
  '9,105,633,277',
  '312',
  '3',
  '11',
  '87',
  '248',
  '46,149'],
 ['Major Lazer11 day(s) old data',
  '9,071,955,331',
  '276',
  '3',
  '14',
  '70',
  '171',
  '639,142,496'],
 ['Fall Out Boy8 day(s) old data',
  '9,022,025,849',
  '203',
  '0',
  '18',
  '98',
  '170',
  '40,402,029'],
 ['P!nkUp to date data',
  '9,016,841,472',
  '240',
  '1',
  '23',
  '87',
  '181',
  '716,214,519'],
 ['Martin Garrix16 day(s) old data',
  '8,970,964,731',
  '181',
  '2',
  '18',
  '76',
  '143',
  '918,007,849'],
 ['BLACKPINKUp to date data',
  '8,946,547,337',
  '104',
  '0',
  '24',
  '49',
  '104',
  '559,319,185'],
 ['Tyler, The Creator2 day(s) old data',
  '8,921,201,314',
  '152',
  '0',
  '25',
  '93',
  '110',
  '1,887,276,856'],
 ['James Arthur2 day(s) old data',
  '8,894,424,356',
  '154',
  '1',
  '17',
  '68',
  '134',
  '86,678,847'],
 ['Sebastian Yatra2 day(s) old data',
  '8,868,875,753',
  '119',
  '0',
  '25',
  '73',
  '108',
  '2,416,699,376'],
 ['Frank Ocean2 day(s) old data',
  '8,827,904,295',
  '45',
  '0',
  '23',
  '45',
  '45',
  '2,567,537,457']]

In [5]:
# Crear el dataframe con los datos obtenidos
df = pd.DataFrame(data, columns=['Artist', 'Lead Stream', 'Tracks', '1b', '100m', '10m', '1m', 'Feat Streams'])

# Imprimir el dataframe
print(df)

                                 Artist     Lead Stream Tracks  1b 100m  10m  \
0                Drake2 day(s) old data  56,194,988,475    282   7  148  275
1            Bad Bunny2 day(s) old data  51,189,983,147    162   9  121  157
2           Taylor SwiftUp to date data  42,204,571,789    353   2  128  277
3             Ed SheeranUp to date data  41,120,157,022    251  11   67  187
4           The Weeknd1 day(s) old data  39,704,788,932    219  10   80  148
..                                  ...             ...    ...  ..  ...  ...
95             BLACKPINKUp to date data   8,946,547,337    104   0   24   49
96  Tyler, The Creator2 day(s) old data   8,921,201,314    152   0   25   93
97        James Arthur2 day(s) old data   8,894,424,356    154   1   17   68
98     Sebastian Yatra2 day(s) old data   8,868,875,753    119   0   25   73
99         Frank Ocean2 day(s) old data   8,827,904,295     45   0   23   45

     1m    Feat Streams
0   279  20,329,715,771
1   160   7,541,244,342
2   341     471,196,255
3   228   3,082,734,708
4   185   6,540,530,184
..  ...             ...
95  104     559,319,185
96  110   1,887,276,856
97  134      86,678,847
98  108   2,416,699,376
99   45   2,567,537,457

[100 rows x 8 columns]

In [6]:
import re #Importamos expresiones regulares para poder limpiar la columna artistas.

df['Artist'] = df['Artist'].apply(lambda x: re.sub('\d+\sday\(s\) old data', '', x))
df['Artist'] = df['Artist'].str.replace('Up to date data', '')

# Imprimir el dataframe resultante
print(df)

                Artist     Lead Stream Tracks  1b 100m  10m   1m  \
0                Drake  56,194,988,475    282   7  148  275  279
1            Bad Bunny  51,189,983,147    162   9  121  157  160
2         Taylor Swift  42,204,571,789    353   2  128  277  341
3           Ed Sheeran  41,120,157,022    251  11   67  187  228
4           The Weeknd  39,704,788,932    219  10   80  148  185
..                 ...             ...    ...  ..  ...  ...  ...
95           BLACKPINK   8,946,547,337    104   0   24   49  104
96  Tyler, The Creator   8,921,201,314    152   0   25   93  110
97        James Arthur   8,894,424,356    154   1   17   68  134
98     Sebastian Yatra   8,868,875,753    119   0   25   73  108
99         Frank Ocean   8,827,904,295     45   0   23   45   45

      Feat Streams
0   20,329,715,771
1    7,541,244,342
2      471,196,255
3    3,082,734,708
4    6,540,530,184
..             ...
95     559,319,185
96   1,887,276,856
97      86,678,847
98   2,416,699,376
99   2,567,537,457

[100 rows x 8 columns]

In [7]:
df.to_csv('Most_Streaming_Spotify.csv', sep='|')